### ISSUE TITLE
geojson-4.1.3 fails to compile with validation-1.2.2

### ISSUE THREAD

**Issue by alaendle** [zellige/hs-geojson#36]
E.g.
```
       /home/curators/work/unpack-dir/unpacked/geojson-4.1.3-7caf89f66b6d2f6e063c7bfe868d42a666f80c7eb13f9f1ac9a76858c5df6450/src/Data/LinearRing.hs:122:39: error: [GHC-76037]
           Not in scope: type constructor or class ‘Validation.Validate’
           Note: The module ‘Data.Validation’ does not export ‘Validate’.
           Suggested fix:
             Perhaps use one of these:
               ‘Validation.Validator’ (imported from Data.Validation),
               ‘Validation.Validation’ (imported from Data.Validation),
               ‘Validation.Validator'’ (imported from Data.Validation)
           |
       122 | fromListWithEqCheck :: (Eq a, Show a, Validation.Validate v, Applicative (v (NonEmpty (ListToLinearRingError a)))) => [a] -> v (NonEmpty (ListToLinearRingError a)) (Lin
earRing a)
           |                                       ^^^^^^^^^^^^^^^^^^^
```

Disabled the package on stackage for the moment (fyi @newmana).

**Comment by noinia** [comment]
It seems there are some changes to the api of validation in validation 1.2; so the current upperbound on validation is too lax; the package requires < 1.2.

I guess this package should switch to the new interface at some point though.

**Comment by newmana** [comment]
Yup my mistake.
