### ISSUE TITLE
Test suite doesn't compile with hspec 2.8

### ISSUE THREAD

**Issue by sternenseemann** [zellige/hs-geojson#29]
```
[ 1 of 10] Compiling Arbitrary        ( test/Arbitrary.hs, dist/build/geojson-test/geojson-test-tmp/Arbitrary.o )
[ 2 of 10] Compiling Data.LineStringTests ( test/Data/LineStringTests.hs, dist/build/geojson-test/geojson-test-tmp/Data/LineStringTests.o )

test/Data/LineStringTests.hs:11:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘Spec’
   |
11 |   ( Spec,
   |     ^^^^

test/Data/LineStringTests.hs:12:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘context’
   |
12 |     context,
   |     ^^^^^^^

test/Data/LineStringTests.hs:13:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘describe’
   |
13 |     describe,
   |     ^^^^^^^^

test/Data/LineStringTests.hs:14:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘it’
   |
14 |     it,
   |     ^^

test/Data/LineStringTests.hs:15:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘shouldBe’
   |
15 |     shouldBe,
   |     ^^^^^^^^
[ 3 of 10] Compiling Data.LinearRingTests ( test/Data/LinearRingTests.hs, dist/build/geojson-test/geojson-test-tmp/Data/LinearRingTests.o )

test/Data/LinearRingTests.hs:12:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘Spec’
   |
12 |   ( Spec,
   |     ^^^^

test/Data/LinearRingTests.hs:13:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘context’
   |
13 |     context,
   |     ^^^^^^^

test/Data/LinearRingTests.hs:14:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘describe’
   |
14 |     describe,
   |     ^^^^^^^^

test/Data/LinearRingTests.hs:15:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘it’
   |
15 |     it,
   |     ^^

test/Data/LinearRingTests.hs:16:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘shouldBe’
   |
16 |     shouldBe,
   |     ^^^^^^^^
[ 4 of 10] Compiling Data.SeqHelperTests ( test/Data/SeqHelperTests.hs, dist/build/geojson-test/geojson-test-tmp/Data/SeqHelperTests.o )

test/Data/SeqHelperTests.hs:8:26: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘Spec’
  |
8 | import Test.Tasty.Hspec (Spec, describe, it, shouldBe, testSpec)
  |                          ^^^^

test/Data/SeqHelperTests.hs:8:32: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘describe’
  |
8 | import Test.Tasty.Hspec (Spec, describe, it, shouldBe, testSpec)
  |                                ^^^^^^^^

test/Data/SeqHelperTests.hs:8:42: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘it’
  |
8 | import Test.Tasty.Hspec (Spec, describe, it, shouldBe, testSpec)
  |                                          ^^

test/Data/SeqHelperTests.hs:8:46: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘shouldBe’
  |
8 | import Test.Tasty.Hspec (Spec, describe, it, shouldBe, testSpec)
  |                                              ^^^^^^^^
[ 5 of 10] Compiling Fixture          ( test/Fixture.hs, dist/build/geojson-test/geojson-test-tmp/Fixture.o )
[ 6 of 10] Compiling Data.Geospatial.Internal.GeometryTests ( test/Data/Geospatial/Internal/GeometryTests.hs, dist/build/geojson-test/geojson-test-tmp/Data/Geospatial/Internal/GeometryTests.o )

test/Data/Geospatial/Internal/GeometryTests.hs:12:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘Spec’
   |
12 |   ( Spec,
   |     ^^^^

test/Data/Geospatial/Internal/GeometryTests.hs:13:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘describe’
   |
13 |     describe,
   |     ^^^^^^^^

test/Data/Geospatial/Internal/GeometryTests.hs:14:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘it’
   |
14 |     it,
   |     ^^

test/Data/Geospatial/Internal/GeometryTests.hs:15:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘shouldBe’
   |
15 |     shouldBe,
   |     ^^^^^^^^
[ 7 of 10] Compiling Data.Geospatial.Internal.GeoFeatureTests ( test/Data/Geospatial/Internal/GeoFeatureTests.hs, dist/build/geojson-test/geojson-test-tmp/Data/Geospatial/Internal/GeoFeatureTests.o )

test/Data/Geospatial/Internal/GeoFeatureTests.hs:7:26: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘Spec’
  |
7 | import Test.Tasty.Hspec (Spec, describe, it, shouldBe, testSpec)
  |                          ^^^^

test/Data/Geospatial/Internal/GeoFeatureTests.hs:7:32: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘describe’
  |
7 | import Test.Tasty.Hspec (Spec, describe, it, shouldBe, testSpec)
  |                                ^^^^^^^^

test/Data/Geospatial/Internal/GeoFeatureTests.hs:7:42: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘it’
  |
7 | import Test.Tasty.Hspec (Spec, describe, it, shouldBe, testSpec)
  |                                          ^^

test/Data/Geospatial/Internal/GeoFeatureTests.hs:7:46: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘shouldBe’
  |
7 | import Test.Tasty.Hspec (Spec, describe, it, shouldBe, testSpec)
  |                                              ^^^^^^^^
[ 8 of 10] Compiling Data.Geospatial.Internal.GeoFeatureCollectionTests ( test/Data/Geospatial/Internal/GeoFeatureCollectionTests.hs, dist/build/geojson-test/geojson-test-tmp/Data/Geospatial/Internal/GeoFeatureCollectionTests.o )

test/Data/Geospatial/Internal/GeoFeatureCollectionTests.hs:7:26: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘Spec’
  |
7 | import Test.Tasty.Hspec (Spec, describe, it, shouldBe, testSpec)
  |                          ^^^^

test/Data/Geospatial/Internal/GeoFeatureCollectionTests.hs:7:32: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘describe’
  |
7 | import Test.Tasty.Hspec (Spec, describe, it, shouldBe, testSpec)
  |                                ^^^^^^^^

test/Data/Geospatial/Internal/GeoFeatureCollectionTests.hs:7:42: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘it’
  |
7 | import Test.Tasty.Hspec (Spec, describe, it, shouldBe, testSpec)
  |                                          ^^

test/Data/Geospatial/Internal/GeoFeatureCollectionTests.hs:7:46: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘shouldBe’
  |
7 | import Test.Tasty.Hspec (Spec, describe, it, shouldBe, testSpec)
  |                                              ^^^^^^^^
[ 9 of 10] Compiling Data.Geospatial.Internal.CRSTests ( test/Data/Geospatial/Internal/CRSTests.hs, dist/build/geojson-test/geojson-test-tmp/Data/Geospatial/Internal/CRSTests.o )

test/Data/Geospatial/Internal/CRSTests.hs:12:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘Spec’
   |
12 |   ( Spec,
   |     ^^^^

test/Data/Geospatial/Internal/CRSTests.hs:13:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘context’
   |
13 |     context,
   |     ^^^^^^^

test/Data/Geospatial/Internal/CRSTests.hs:14:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘describe’
   |
14 |     describe,
   |     ^^^^^^^^

test/Data/Geospatial/Internal/CRSTests.hs:15:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘it’
   |
15 |     it,
   |     ^^

test/Data/Geospatial/Internal/CRSTests.hs:16:5: error:
    Module ‘Test.Tasty.Hspec’ does not export ‘shouldBe’
   |
16 |     shouldBe,
   |     ^^^^^^^^
```

**Comment by newmana** [comment]
Fixed.
